---
- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service start
  service: name=firewalld state=started enabled=yes

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable for SELinux
  selinux: state=disabled
